// Generated by LispyScript v1.0.0
var roleHarvester = require('role.harvester');
var roleUpgrader = require('role.upgrader');
module.exports.loop = function() {
    return (function() {
        (function(o,f,s) {
            var _k = Object.keys(o);
            return (_k).forEach(function(elem) {
                return f.call(s,o[elem],elem,o);
            });
        })(Memory.creeps,function(val,name) {
            return ((!Game.creeps[name]) ?
                (function() {
                    return delete(Memory.creeps[name]);
                })() :
                undefined);
        });
        var harvesters = _.filter(Game.creeps,function(creep) {
            return (creep.memory.role === "harvester");
        });
        console.log(("Harvesters: " + harvesters.length));
        ((harvesters.length < 2) ?
            (function() {
                return (function() {
                    var newName = Game.spawns.Spawn1.createCreep([WORK,CARRY,MOVE],undefined,{role: "harvester"});
                    return console.log(("Spawning new harvester: " + newName));
                })();
            })() :
            undefined);
        return (function(o,f,s) {
            var _k = Object.keys(o);
            return (_k).forEach(function(elem) {
                return f.call(s,o[elem],elem,o);
            });
        })(Game.creeps,function(val,name) {
            return (function() {
                var creep = val;
                ((creep.memory.role === "harvester") ?
                    (function() {
                        return roleHarvester.run(creep);
                    })() :
                    undefined);
                return ((creep.memory.role === "upgrader") ?
                    (function() {
                        return roleUpgrader.run(creep);
                    })() :
                    undefined);
            })();
        });
    })();
};
